[package]
name = "rust-sgx-util"
version = "0.1.0"
authors = ["Jakub Konka <jakub.konka@golem.network>"]
edition = "2018"

[dependencies]
libc = "0.2"
thiserror = "1"

[dev-dependencies]
structopt = "0.3"
anyhow = "1"
